### ISSUE TITLE
Current Octopi release doesn't work with gksu-polkit

### ISSUE THREAD

**Issue by hphilm** [fhdk/gksu-polkit#1]
@fhdk: may you check at this [issue](https://github.com/aarnt/octopi/issues/380)?

**Comment by fhdk** [comment]
The package is a repackage of a debian package designed to replace gksu using polkit.

I may be enough to remove the gksu symlink as the symlink is for backwards compatibility with scripts relying on gksu.

https://github.com/aarnt/octopi/issues/380#issuecomment-498019732

**Comment by hphilm** [comment]
We might need to find a solution in **octopi**. However I wonder why it worked before and breaks now.

**Comment by fhdk** [comment]
I don't I think octopi ever worked with gksu-polkit but I cannot be entirely sure - one thing is sure though - this is the first issue with the package.

I think it is by coincidence that the precise combo of octopi and gksu-polkit as available on the same system or it is because zensu package also offers gksu like options.

```
~ >>> sudo pacman -Syu gksu                                                     
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: There are 2 providers available for gksu:
:: Repository community
   1) gksu-polkit  2) zensu
```

**Comment by fhdk** [comment]
gksu-polkit where and when

https://github.com/manjaro/release-plan/issues/200

**Comment by fhdk** [comment]
https://github.com/aarnt/octopi/issues/380#issuecomment-503769593
